const content = [
    {
        page: 'header',
        subpages: [],
        element01: 'cloud4service',
        element02: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        element03: '',
    },
    {
        page: 'about',
        subpages: [],
        element01: `Willkommen bei Cloud 4 Service
        `,
        element02: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt, ducimus alias quaerat facere quo ipsum incidunt facilis nulla dolorum explicabo. Blanditiis numquam, necessitatibus optio ab repudiandae molestias esse. Doloribus, iusto!',
        element03: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ea unde delectus molestias deleniti voluptate, sit reprehenderit dolores nihil dolore quos.',
        element04: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt sit, quae, rem beatae ducimus tempora ab a, harum odit sunt vero laborum? Asperiores perferendis sint vitae sapiente distinctio similique impedit ut atque quas saepe tempora, vel suscipit aspernatur inventore doloremque?',
    },
    {
        page: 'services',
        subpages: [],
        element01: 'Unser Service für IT-Umzug:',
        element02: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem ut nihil asperiores animi ratione est fuga accusamus dolorem rem deserunt, deleniti quaerat at, maxime molestias odio minus tempora blanditiis eum!',
        element03: 'Wir wissen worauf es bei einem IT-Umzug ankommt!',
        element04: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta animi ad tempora, veritatis repellat assumenda soluta quos aperiam quas voluptates. Ipsum, esse laborum dignissimos provident voluptatibus placeat ea minus harum facilis adipisci modi voluptatem totam corrupti neque perferendis natus fugit.',
        element05: 'Wir sorgen für geringstmögliche Ausfallzeiten und exakte Termineinhaltung.',
        element06: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Earum, rerum ratione. Odio, et esse rerum eum reprehenderit temporibus quis. Dolores excepturi perferendis, similique ipsam hic asperiores quaerat delectus consectetur dolorum sapiente nemo culpa, commodi animi qui eveniet ad aperiam inventore.',
        element07: 'Wir sind da, wenn Sie uns brauchen.',
        element08: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit dignissimos omnis nostrum necessitatibus quibusdam aliquam possimus sint at iusto. Sit odio explicabo delectus, voluptas, alias veritatis repudiandae suscipit ipsum optio, eum nulla consequuntur mollitia. Laborum dolore quod saepe sed officia.',
        element09: 'Am Ende ist alles wie vorher. Oder besser.',
        element10: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Cupiditate sint, est perferendis asperiores culpa nisi incidunt dolore vero non repellat.',
        element11: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Id itaque possimus odio rerum ipsam nulla.',
        element12: 'Unser Service für IT-Outsourcing:',
        element13: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Suscipit aliquam, deleniti et obcaecati ipsa veniam, odio rem in aut non exercitationem tempore, sint ex eius! Magnam architecto in debitis ad.',
        element14: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore eaque aut omnis aliquid atque a aliquam placeat consectetur alias iusto rerum molestias magni nam autem itaque optio voluptatum vel, mollitia assumenda? Facere reprehenderit dolorum id laboriosam sit ducimus odio, vitae quisquam numquam! Corrupti reprehenderit pariatur, nulla quasi ut provident repudiandae?',
        element15: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem, non laudantium recusandae ullam veritatis necessitatibus et consequuntur aperiam, impedit rerum qui. Eaque quos et quam debitis ab natus tempora cumque!',
        element16: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur sunt officia modi repellendus soluta sint tempora magnam culpa sequi quis!',
        element17: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatibus earum modi animi quaerat porro, eum repellendus voluptate sunt sequi aut? Architecto nisi officiis consequatur recusandae neque eos laudantium repudiandae sunt?',
        element18: 'Outsourcing-Analyse',
        element19: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus repudiandae, distinctio rem quaerat asperiores possimus.',
        element20: 'Analyse und Bewertung',
        element21: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint dolorem quibusdam deleniti expedita quam pariatur.',
        element22: 'Planung und Überwachung',
        element23: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Aspernatur dignissimos illum natus quibusdam minima! Dolore!',
        element24: 'Relationship Management',
        element25: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit, nisi explicabo doloremque fuga eveniet illum!',
        element26: 'Vertragsende',
        element27: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Praesentium, provident magni animi rerum consequatur natus.',
        element28: 'Vertrag',
        element29: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquam iure officiis beatae velit repellat aliquid.',
        element30: 'Unser Service für IT-Konsolidierung:',
        element31: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo assumenda a deleniti dolorem eaque. Repudiandae?',
        element32: 'Unterstützung bei Konsolidierungsmaßnahmen',
        element33: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facilis ratione culpa doloribus mollitia illo fugit dolores, rerum impedit voluptates, debitis eveniet perferendis inventore! Unde atque voluptatibus veritatis. Veritatis, libero aperiam iure incidunt repellendus quis quam. Fuga reprehenderit consequatur nobis modi?',
        element34: 'Migrationen in virtuelle Umgebungen',
        element35: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui et laborum sequi fugiat eligendi praesentium esse, quidem repellendus explicabo. Aliquid possimus veritatis animi sed eaque ad magni, consectetur sapiente nulla?',
        element36: 'Hochverfügbarkeitslösungen',
        element37: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Nobis molestiae a praesentium ipsa sapiente nostrum, ex veritatis qui vero repudiandae!',
        element38: 'Virtuelle Infrastrukturen',
        element39: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facilis voluptas excepturi sint qui quae tempora eligendi libero, quia accusantium aspernatur!',    
        element40: 'Komplexität und Kosten reduzieren: IT-Virtualisierung',
        element41: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita molestias corporis quam nulla facere, quod a facilis amet laboriosam animi voluptates qui doloremque incidunt asperiores dolorum aliquid magni recusandae exercitationem suscipit hic omnis praesentium esse. Est et quidem assumenda consectetur?',
    },
    {
        page: 'clients',
        subpages: [],
        element01: '',
        element02: '',
        element03: '',
    },
    {
        page: 'contact',
        subpages: [],
        element01: 'Nehmen Sie noch heute mit uns den Kontakt auf!',
        element02: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit.',
        element03: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Necessitatibus, minima.'
    }
]

export default content;